services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: coeusdevops/coeus-app:0.1
    container_name: coeus-app
    environment:
      DB_USER: coeususer
      DB_PASSWORD: 123456
      DB_NAME: coeusapp
      DB_HOST: db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - coeus-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Coeus123
    networks:
      - coeus-app
networks:
  coeus-app:
    external: true