# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql:8
    container_name: coeus-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Coeus123
      MYSQL_DATABASE: coeusapp
      MYSQL_USER: coeususer
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - coeus-app
networks:
  coeus-app:
    external: true