name: Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - rmse-dev
          - rmse-qa
          - rmse-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VM_IP: ${{ steps.set-ip.outputs.vm_ip }}

    steps:
      - name: Set VM IP Address
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "rmse-dev" ]]; then
            echo "VM_IP=128.2.1.2" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "rmse-qa" ]]; then
            echo "VM_IP=128.2.1.3" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "rmse-prod" ]]; then
            echo "VM_IP=128.2.1.4" >> $GITHUB_ENV
          fi

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy to ${{ github.event.inputs.environment }} Environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} Environment..."
          echo "Connecting to VM with IP: $VM_IP"
          echo "VM IP Address is: $VM_IP"
