name: Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - dev
          - int
          - cons
          - prod

jobs:
  deploy-dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy to Dev Environment
        run: |
          echo "Deploying to Dev Environment..."
          # Add your specific deployment steps for Dev

  deploy-int:
    if: ${{ github.event.inputs.environment == 'int' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy to Int Environment
        run: |
          echo "Deploying to Int Environment..."
          # Add your specific deployment steps for Int

  deploy-cons:
    if: ${{ github.event.inputs.environment == 'cons' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy to Cons Environment
        run: |
          echo "Deploying to Cons Environment..."
          # Add your specific deployment steps for Cons

  deploy-prod:
    if: ${{ github.event.inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy to Prod Environment
        run: |
          echo "Deploying to Prod Environment..."
          # Add your specific deployment steps for Prod
